"""empty message

Revision ID: 6234c15e812d
Revises: bf71f950af7d
Create Date: 2018-02-17 17:13:44.106116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6234c15e812d'
down_revision = 'bf71f950af7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('problem', sa.Column('is_urgent', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('problem', 'is_urgent')
    # ### end Alembic commands ###
