"""empty message

Revision ID: 9ead449e06b4
Revises: 8dc13cc4a2ea
Create Date: 2018-02-14 19:23:51.088647

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ead449e06b4'
down_revision = '8dc13cc4a2ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('problem', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_problem_timestamp'), 'problem', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_problem_timestamp'), table_name='problem')
    op.drop_column('problem', 'timestamp')
    # ### end Alembic commands ###
