#!/usr/bin/env python3
import pickle
from datetime import datetime
from time import sleep
import paho.mqtt.client as mqtt

CLIENT = mqtt.Client()
CLIENT.connect("34.242.137.167", 1883, 60)


def check_send_time():
    now = datetime.utcnow()
    CLIENT.publish("test_data_send", payload=pickle.dumps(now))
    sleep(0.1)

for i in range(10000):
    print(i)
    check_send_time()

